name: Build and test Node.js application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: self-hosted

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies    
      run: npm install
      
    - name: Run test
      run: npm test

  run_npm_security_scan:
    needs: build_and_test

    runs-on: self-hosted

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies    
      run: npm install

    - name: Run security scan with npm audit
      run: npm audit

  deploy:
    needs: run_npm_security_scan

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: self-hosted

    steps:
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.7
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        wait_deploy: true
