name: Build and test Node.js application

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies    
      run: npm install
      
    - name: Run test
      run: npm test

  deploy:
    needs: build_and_test

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.7
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
